name: shamell_flutter
description: Minimal client for alias linking and @alias transfers
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^3.5.7
  web_socket_channel: ^2.4.0
  geolocator: ^10.1.0
  webview_flutter: ^4.7.0
  qr_flutter: ^4.1.0
  connectivity_plus: ^6.0.3
  app_links: ^6.3.2
  workmanager: ^0.9.0+3
  pinenacl: ^0.6.0
  crypto: ^3.0.3
  flutter_local_notifications: ^17.2.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  share_plus: ^10.0.2
  flutter_contacts: ^1.1.7
  google_maps_flutter: ^2.7.0
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.1
  url_launcher: ^6.3.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  local_auth: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#111827"
  adaptive_icon_foreground: assets/icon.png

flutter_native_splash:
  color: "#111827"
  android_12:
    color: "#111827"
